services:
  postgres:
    container_name: storage-system-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - storage_system_pg:/data/postgres

  minio:
    image: docker.io/bitnami/minio:2022
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_MESSAGING_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_MESSAGING_PASSWORD}

volumes:
  storage_system_pg:
    external: false
  minio_data:
    driver: local